version: '3'

services: 
    web:
        build: .
        command: python3 manage.py runserver
        ports:
            - 8000:8000
            
    # Source: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
            soft: -1
            hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic