# Generated by Django 3.2.3 on 2021-07-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiscDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILENAME', models.TextField()),
                ('PG_NUM', models.IntegerField()),
                ('DOC_TEXT', models.TextField()),
            ],
        ),
    ]
